version: '3.8'

services:
  expresspp:
    build: .
    container_name: express_ts_app
    ports:
      - "3030:3030"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
      - redis
  db:
    image: mysql:8.0
    container_name: express_ts_db
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    restart: always
    environment:
      MYSQL_DATABASE: api_ts_express
      MYSQL_ROOT_PASSWORD: abc123198809
    volumes:
      - dbdata:/var/lib/mysql
  redis:
    image: redis
    container_name: express_ts_redis
    ports:
      - "6379:6379"


volumes:
  dbdata: